#!/usr/bin/env python3
import os

from jinja2 import Template


def gen_implementation(c1, c2):
    lines = []
    for c in range(c2):
        expr = f"mm_mullo_epi32_compat(m1[0], _mm_set1_epi32(m2[{c}][0]))"
        for k in range(1, c1):
            expr = f"_mm_add_epi32({expr}, mm_mullo_epi32_compat(m1[{k}], _mm_set1_epi32(m2[{c}][{k}])))"
        lines.append(f"    out[{c}] = {expr};")
    return lines


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    template_path = os.path.join(script_dir, "templates/matrix_multiply_simd.tpp.j2")
    with open(template_path) as f:
        template = Template(f.read())
    print("// Generated by matrix_multiply_v4sf.py\n")
    for c1 in range(2, 5):
        for r1 in range(2, 5):
            for c2 in range(2, 5):
                if r1 == c2:
                    keys = {
                        "C1": c1,
                        "R1": r1,
                        "C2": c2,
                        "R2": c1,
                        "type": "__v4si",
                        "implementation": gen_implementation(c1, c2)
                    }
                    print(template.render(**keys))

if __name__ == "__main__":
    main()