#!/usr/bin/env python3
import os
import sys

from jinja2 import Template


def main():
    if len(sys.argv) != 2:
        print("Usage: python3 vector_type.py <Number>")
        sys.exit(1)
    N = int(sys.argv[1])
    script_dir = os.path.dirname(os.path.abspath(__file__))
    template_path = os.path.join(script_dir, "templates/vector.tpp.j2")
    with open(template_path) as f:
        template = Template(f.read())
    print("// Generated by vector_type.py\n")

    keys = {
        "N": N
    }
    print(template.render(**keys))


if __name__ == "__main__":
    main()
